# Generated by Django 2.1.5 on 2019-02-13 22:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('height', models.FloatField(help_text='in inches')),
                ('usual_weight', models.PositiveSmallIntegerField(help_text='in lbs')),
                ('frame_type', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], help_text='based off wrist size', max_length=1)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(help_text='in lbs')),
                ('bmi', models.FloatField(verbose_name='body mass index')),
                ('body_fat', models.FloatField(help_text='as %')),
                ('skeletal_muscle', models.FloatField(help_text='as %')),
                ('resting_metabolism', models.FloatField(help_text='in kcal')),
                ('body_age', models.PositiveSmallIntegerField()),
                ('visceral_fat_level', models.PositiveSmallIntegerField()),
                ('waist_circumference', models.FloatField(blank=True, help_text='in cm', null=True)),
                ('activity_rating', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sedentary (Little or no exercise)'), (1, 'Lightly Active (Light exercise or sports 1 to 3 days per week)'), (2, 'Moderately Active (Moderate exercise or sports 3 to 5 days per week)'), (3, 'Very Active (Hard exercise or sports 6 to 7 days per week)'), (4, 'Extra Active (Very hard exercise or sports 6 to 7 days per week + Physical job)')], null=True)),
                ('total_energy_intake', models.FloatField(blank=True, help_text='in kcal', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='biometrics.Client')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('client', 'date')},
        ),
    ]
