# Generated by Django 2.1.5 on 2019-03-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.FloatField(help_text='inches'),
        ),
        migrations.AlterField(
            model_name='client',
            name='usual_weight',
            field=models.PositiveSmallIntegerField(help_text='lbs'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='bmi',
            field=models.FloatField(blank=True, null=True, verbose_name='body mass index'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body_fat',
            field=models.FloatField(blank=True, help_text='%', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='resting_metabolism',
            field=models.FloatField(blank=True, help_text='kcal', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='skeletal_muscle',
            field=models.FloatField(blank=True, help_text='%', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='total_energy_intake',
            field=models.FloatField(blank=True, help_text='kcal', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='visceral_fat_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='waist_circumference',
            field=models.FloatField(blank=True, help_text='cm', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='weight',
            field=models.FloatField(help_text='lbs'),
        ),
    ]
